Update step08-apply-helm-chart.sh
Problem:
Once you run the helm command, you will see the following error if your kubectl context is set to the previously created cluster.

```
Error: Kubernetes cluster unreachable: Get "https://<cluster-id>.gr7.us-west-2.eks.amazonaws.com/version": dial tcp: lookup <cluster-id>.gr7.us-west-2.eks.amazonaws.com: no such host
```

Solution:
You need to update the cluster context in kubeconfig file to the newly created cluster in the last step.
```
# Set context to the newly created cluster.
aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_DEFAULT_REGION}
```