Remove comment after wait command
The comment after the wait command causes the `helm upgrade` command to fail with the following message:
> Error: "helm upgrade" requires 2 arguments

Removing the comment fixes this error.